-- https://school.programmers.co.kr/learn/courses/30/lessons/301647
-- 코드를 작성해주세요
SELECT CHILD.ID AS 'ID', CHILD.GENOTYPE AS 'GENOTYPE', PARENT.GENOTYPE AS 'PARENT_GENOTYPE'
FROM ECOLI_DATA AS CHILD
    INNER JOIN ECOLI_DATA AS PARENT ON CHILD.PARENT_ID LIKE PARENT.ID
WHERE (CHILD.GENOTYPE & PARENT.GENOTYPE) LIKE PARENT.GENOTYPE
ORDER BY CHILD.ID ASC
