-- https://school.programmers.co.kr/learn/courses/30/lessons/131120
-- 코드를 입력하세요
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE GENDER LIKE 'W' AND MONTH(DATE_OF_BIRTH) LIKE "3" AND TLNO IS NOT NULL
ORDER BY MEMBER_ID ASC
