-- https://school.programmers.co.kr/learn/courses/30/lessons/298518
-- 코드를 작성해주세요
SELECT COUNT(ID) AS 'FISH_COUNT'
FROM FISH_INFO 
WHERE FISH_TYPE IN
(
    SELECT FISH_TYPE
    FROM FISH_NAME_INFO
    WHERE FISH_NAME LIKE 'BASS' OR FISH_NAME LIKE 'SNAPPER'
)
